#ifndef VGA_COLORS_H
#define VGA_COLORS_H

#define VGA_FG_BLACK 0x0
#define VGA_FG_BLUE 0x1
#define VGA_FG_GREEN 0x2
#define VGA_FG_CYAN 0x3
#define VGA_FG_RED 0x4
#define VGA_FG_MAGENTA 0x5
#define VGA_FG_BROWN 0x6
#define VGA_FG_GRAY 0x7
#define VGA_FG_DARK_GRAY 0x8
#define VGA_FG_BRIGHT_BLUE 0x9
#define VGA_FG_BRIGHT_GREEN 0xA
#define VGA_FG_BRIGHT_CYAN 0xB
#define VGA_FG_BRIGHT_RED 0xC
#define VGA_FG_BRIGHT_MAGENTA 0xD
#define VGA_FG_YELLOW 0xE
#define VGA_FG_WHITE 0xF

#define VGA_BG_BLACK VGA_FG_BLACK<<4
#define VGA_BG_BLUE VGA_FG_BLUE<<4
#define VGA_BG_GREEN VGA_FG_GREEN<<4
#define VGA_BG_CYAN VGA_FG_CYAN<<4
#define VGA_BG_RED VGA_FG_RED<<4
#define VGA_BG_MAGENTA VGA_FG_MAGENTA<<4
#define VGA_BG_BROWN VGA_FG_BROWN<<4
#define VGA_BG_GRAY VGA_FG_GRAY<<4
#define VGA_BG_DARK_GRAY VGA_FG_DARK_GRAY<<4
#define VGA_BG_BRIGHT_BLUE VGA_FG_BRIGHT_BLUE<<4
#define VGA_BG_BRIGHT_GREEN VGA_FG_BRIGHT_GREEN<<4
#define VGA_BG_BRIGHT_CYAN VGA_FG_BRIGHT_CYAN<<4
#define VGA_BG_BRIGHT_RED VGA_FG_BRIGHT_RED<<4
#define VGA_BG_BRIGHT_MAGENTA VGA_FG_BRIGHT_MAGENTA<<4
#define VGA_BG_YELLOW VGA_FG_YELLOW<<4
#define VGA_BG_WHITE VGA_FG_WHITE<<4

#endif